<template>
  <div class="container">
    <div class="info">
      <h2>For: {{ movie.name }}</h2>
      <p>{{ movie.startTime }}</p>
      <p>{{ movie.language }}</p>
      <!-- Show age restriction when it is not null-->
      <p v-if="movie.ageRestriction" id="age">Age restriction: {{ movie.ageRestriction }}</p>

      <div class="purchase">
        <input id="nrOfTickets" @onClick="buyTickets" type="number" value="1" min="1" max="4"
               v-model="selectedTickets"/>
        <button id="buy" @Click="buyTickets">Buy</button>
      </div>
    </div>
    <div class="layout">
      <h2>Cinema layout</h2>
      <div class="cinema">
        <!-- seat class generated by AI-->
        <div v-for="(seat, index) in movie.seats.split('')" :key="index" class="seat"
             :class="{ taken: seat === '1', recommended: recommendedSeats.includes(index) }">
        </div>
      </div>
    </div>
  </div>
</template>


<script>
import axios from "axios";

export default {
  props: {
    movie: Object
  },

  data() {
    return {
      selectedTickets: 1,
      recommendedSeats: []
    };
  },

  methods: {
    recommendSeats() { // This function is generated by AI
      let availableSeats = [];
      this.movie.seats.split('').forEach((seat, index) => {
        if (seat === '0') {
          availableSeats.push(index);
        }
      });

      // Recommend as many seats as the number of selected tickets, as long as there are enough available seats
      if (availableSeats.length >= this.selectedTickets) {
        this.recommendedSeats = availableSeats.slice(0, this.selectedTickets);
      } else {
        // If there aren't enough available seats, recommend all available seats
        this.recommendedSeats = availableSeats;
      }
    },

    buyTickets() { // This function is generated by AI
      // Update the seats data to mark the recommended seats as taken
      let seatsArray = this.movie.seats.split('');
      this.recommendedSeats.forEach(seatIndex => {
        seatsArray[seatIndex] = '1';
      });
      let updatedSeats = seatsArray.join('');

      // Create a copy of the movie data with the updated seats
      let updatedMovie = { ...this.movie, seats: updatedSeats };

      // Send a request to the backend to update the movie data
      axios.put(`http://localhost:8080/api/movies/${this.movie.id}`, updatedMovie)
          .then(() => {
            console.log('Movie data updated successfully');
            // Emit an event to the parent component with the updated movie data
            this.$emit('updateMovie', updatedMovie);
          })
          .catch(error => {
            console.error('Failed to update movie data', error);
          });
    }

  },

  watch: {
    selectedTickets() {
      this.recommendSeats();
    }
  },

  mounted() {
    this.recommendSeats();
  }
}
</script>


<style scoped>
.container {
  display: flex;
  flex-direction: row;
  justify-content: space-evenly;
}

.info {
  display: flex;
  flex-direction: column;
  width: 200px;
  padding: 25px;
  background: #3D5A80;
  border-radius: 10px;
}

.info p {
  align-self: center;
  margin: 0 0 15px;
}

.purchase {
  display: flex;
  justify-content: center;
  gap: 10px;
}

#nrOfTickets {
  width: 30px;
  color: #293241;
}

#buy {
  margin-top: 5px;
  border: none;
  border-radius: 5px;
  padding: 3px;
  width: 70px;
  background: #EE6C4D;
}

#buy:hover {
  color: #293241;
  background: #E0FBFC;
  cursor: pointer;
}

.layout {
  display: flex;
  flex-direction: column;
  justify-content: center;
  width: 500px;
  padding: 25px;
  background: #3D5A80;
  border-radius: 10px;
}

/* generated by AI*/
.cinema {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 10px;
}

/* generated by AI*/
.seat {
  width: 20px;
  height: 20px;
  background-color: #E0FBFC;
}

/* generated by AI*/
.seat.taken {
  background-color: #293241;
}

/* generated by AI*/
.seat.recommended {
  background-color: #8ade8a;
}

</style>
